### ISSUE TITLE
More than one keyword

### ISSUE THREAD

**Issue by TarmacD** [qztseng/google-trends-daily#2]
I did not yet edit the code so that it works for more than one keyword (Google, repectively gtrends allows 5 keywords at once). Does anybody eddited the code? Is there a simple way, I think there might be an issue with shifting the timeframe for next iteration...

**Comment by qztseng** [comment]
The Google API support more than one keyword. The reason it was not explicitly implemented is because I haven't got a clear usage scenario of how to do normalization/scaling across different keywords.
