### ISSUE TITLE
A Few Follow up Questions

### ISSUE THREAD

**Issue by mcui123** [qztseng/google-trends-daily#3]
Hi Qingzong, 

Great work! Your post on Medium is the most comprehensive approach I have seen re: getting daily trend data from Google Trend. 

I have a few follow up questions for you if you wouldn't mind: 

1. For the "overlapping" method: 

(a) What is the rationale for choosing 100 days as the overlapping period? 

(b) How exactly does renormalization work? Let's say we have 500 days. The algorithm you wrote (gtrend.get_daily_trend) downloads 2 piece-wise trend data: Day 1 - Day 300 & Day 201 - Day 500. The 100 days overlapping period (Day 201 to Day 300) is used as the "scale" for renormalization. I reset the maximum value from that 100 days to have a value of 100 and subsequently rescale the rest of the data in the non-overlapping days (Day 1 - Day 200 & Day 301 - Day 500)... Is this a correct understanding of how the renormalization algorithm work?

(c) From a conceptual perspective, I am wondering what is the rationale for the "overlapping" method performing better than "dailydata" method? And why would "overlapping" method consistently have lower values than "dailydata" method when search horizon > 90 days? 

2. One core functionality of Google Trend is that, it's able to further break down trend data by geography. I am wondering if it's possible to extract daily **geographical information** as well (I am looking at US states level, e.g. CA, GA, NY etc.)? 

Much appreciation for your great work! 

Best Regards, 
Jessie

**Comment by qztseng** [comment]
a) The 100 days was chosen empirically, as long as there is sufficient signals (search volume) within this overlap period, it should be fine. Avoid normalizing using an overlapping period where you get only baseline noises (very low search volume)

b)  More or less like that. The overlapping period not necessarily has maximum of 100, the code worked as below: (that is also why you need to have sufficient search volume at overlapping period)
```
y1 = temp.loc[overlap_start:end_d].iloc[:,0].values.max()
y2 = df.loc[overlap_start:end_d].iloc[:,-1].values.max()
coef = y2/y1
temp = temp * coef
```
c) The dailydata method matches the fragments of daily result with overall monthly (or weekly) results, but the monthly/weekly peak is already smoothed over that period (i.e actual search peak happened only on sunday, but the weekly trend will average this peak with the search trend of the rest of the week) , so the scaling won't match exactly as underlying daily data. 

2) the get_daily_trend function can accept geological argument
`get_daily_trend(trendreq, keyword:str, start:str, end:str, cat=0, 
                    geo='', gprop='', delta=269, overlap=100, sleep=0, 
                    tz=0, verbose=False)`
You just need to know the correct geo code and feed it to the function. Be careful about the timezone difference. You might need to experiment a little bit to get it right.

**Comment by mcui123** [comment]
Thanks @qztseng  for your response! 

Just to follow up on the specific example I used in 2(b) for some clarifications: 

Let's say, in that 100-day overlapping period between Day 200 - Day 300:
- Day 210 from **1st piece-wise trend data** has a value of 75. It is not the max value for D1- D300, but it is the max value for D200-300. 
- Day 210 from **2nd piece-wise trend data** has a value of 85. It is not the max value for D200- D500, but it is the max value for D200-300. 
- My understanding is that, we calculate 85/75 = 1.13  as the rescaling coefficient. Then we multiply all the remaining data in first & second piece (or first piece only?) by that coefficient.... is this understanding correct? 

Then, for geographical information:

If I would like to get the daily data for each state in US over a longer time horizon, I would need to run this whole algorithm for **each state separately** by putting in the correct parameter for 'geo' and 'tz', correct? 

Again, much appreciation! 

Best Regards, 
Jessie

**Comment by qztseng** [comment]
To be more precise, the timeframe iteration goes from the end date backward. (D500-200, D300-D1)
And it is always the lastest timeframe get scaled (D500-D200 fetched first, and then D300-D1. Use overlap of D200-D300 to get the scaling factor. Scale D300-D1 using this factor)

For multiple geological location, you might want to check the pytrends' doc for detailed explanation
https://github.com/GeneralMills/pytrends

**Comment by mcui123** [comment]
> To be more precise, the timeframe iteration goes from the end date backward. (D500-200, D300-D1)
> And it is always the lastest timeframe get scaled (D500-D200 fetched first, and then D300-D1. Use overlap of D200-D300 to get the scaling factor. Scale D300-D1 using this factor)
> 
> For multiple geological location, you might want to check the pytrends' doc for detailed explanation
> https://github.com/GeneralMills/pytrends

Thanks so much! This is extremely helpful. 

Best Regards, 
Jessie
